project:
  type: book

book:
  title: "Is the Australian Benefit System fit for purpose?"
  author: "Matt Nolan"
  date: "16/08/2024"
  chapters:
    - index.qmd
    - 01-summary.qmd
    - 01b-RN.qmd
    - 02-introduction.qmd
    - 03-hypothetical.qmd
    #- 04-international.qmd
    #- 05-evidence.qmd
    - 06-iron.qmd
    - 07-insurance.qmd
    - 08-policy.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true  # Ensure the table of contents is enabled
    number-sections: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true

editor: visual


